// ---------------------------------------------------------------------------
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by tools/generate_cpp.py from data/*.yaml
// Schema version: 1
// SPDX-License-Identifier: MIT
// ---------------------------------------------------------------------------
#ifndef SIMCOM_DATABASE_HPP
#define SIMCOM_DATABASE_HPP

#include "simcom_types.hpp"

namespace simcom {

// ---------------------------------------------------------------------------
// Static database - 9 modules
//  0: SIM800L  |  1: SIM800C  |  2: SIM808  |  3: SIM868  |  4: SIM800A
//  5: SIM800F  |  6: SIM800H  |  7: SIM800   |  8: SIM800C-DS
// ---------------------------------------------------------------------------
inline constexpr ModuleSpec MODULES[] = {
    // 0) SIM800L
    {
        "SIM800L",
        { "LGA", 88, 3400, 4400, 2048,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { false, false, true, true, true, true, true, true, 3, 1, 1,
          false, false, false, false, false, false, false, false },
        { true, 3, 3, true, 0, true, "PIN5", "", JammingPin::PIN5 }
    },
    // 1) SIM800C
    {
        "SIM800C",
        { "SMT", 42, 3400, 4400, 4096,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { true, false, false, true, false, false, false, false, 0, 1, 0,
          false, false, false, false, false, false, false, false },
        { true, 2, 2, true, 2, false, "PIN29", "", JammingPin::PIN29 }
    },
    // 2) SIM808
    {
        "SIM808",
        { "SMT", 68, 3400, 4400, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { true, true, false, true, true, true, true, true, 2, 2, 2,
          false, false, false, false, false, false, false, false },
        { true, 3, 3, true, 2, true, "PIN63", "", JammingPin::PIN63 }
    },
    // 3) SIM868
    {
        "SIM868",
        { "SMT+LGA", 77, 3400, 4400, 4096,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { true, true, false, true, false, true, true, true, 2, 1, 0,
          false, false, false, false, false, false, false, false },
        { true, 3, 3, true, 2, true, "PIN29", "", JammingPin::PIN29 }
    },
    // 4) SIM800A
    {
        "SIM800A",
        { "SMT", 68, 3400, 4400, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { true, false, false, true, true, false, false, true, 3, 1, 2,
          false, false, false, false, false, false, false, false },
        { false, 2, 2, true, 2, false, "PIN67", "", JammingPin::PIN67 }
    },
    // 5) SIM800F
    {
        "SIM800F",
        { "SMT", 68, 3400, 4400, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { true, false, false, true, true, false, false, true, 3, 1, 2,
          false, false, false, false, false, false, false, false },
        { true, 2, 2, true, 2, false, "PIN67", "", JammingPin::PIN67 }
    },
    // 6) SIM800H
    {
        "SIM800H",
        { "LGA", 88, 3400, 4400, 4096,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { true, false, true, true, true, true, true, true, 3, 1, 1,
          false, false, false, false, false, false, false, false },
        { true, 3, 3, true, 0, true, "PIN5", "", JammingPin::PIN5 }
    },
    // 7) SIM800
    {
        "SIM800",
        { "SMT", 68, 3400, 4400, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { true, false, false, true, true, false, true, true, 2, 1, 2,
          false, false, false, false, false, false, false, false },
        { true, 2, 2, true, 2, true, "PIN67", "", JammingPin::PIN67 }
    },
    // 8) SIM800C-DS
    {
        "SIM800C-DS",
        { "SMT+LGA", 77, 3400, 4400, 4096,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          SimCardType::UNKNOWN, AntennaType::UNKNOWN, 0, false, false, "", "" },
        { true, false, true, true, false, true, true, true, 2, 1, 0,
          false, false, false, false, false, false, false, false },
        { true, 3, 3, true, 0, true, "PIN29", "ch.21.13: FD not supported", JammingPin::PIN29 }
    }
};

inline constexpr std::size_t MODULE_COUNT =
    sizeof(MODULES) / sizeof(MODULES[0]);

// ---------------------------------------------------------------------------
// ATCommandVersionDelta table
// ---------------------------------------------------------------------------
inline constexpr ATCommandVersionDelta VERSION_DELTAS[] = {
    { "", AtManualVersion::UNKNOWN, AtManualVersion::UNKNOWN, AtManualVersion::UNKNOWN, "" }
};

inline constexpr std::size_t VERSION_DELTA_COUNT =
    sizeof(VERSION_DELTAS) / sizeof(VERSION_DELTAS[0]);

// ---------------------------------------------------------------------------
// ModuleCrossReference table
// ---------------------------------------------------------------------------
inline constexpr ModuleCrossReference CROSS_REFERENCES[] = {
    { "SIM800L",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
    { "SIM800C",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
    { "SIM808",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
    { "SIM868",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
    { "SIM800A",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
    { "SIM800F",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
    { "SIM800H",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
    { "SIM800",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } },
    { "SIM800C-DS",
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
      { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr } }
};

inline constexpr std::size_t CROSS_REFERENCE_COUNT =
    sizeof(CROSS_REFERENCES) / sizeof(CROSS_REFERENCES[0]);

} // namespace simcom

#endif // SIMCOM_DATABASE_HPP
